### ISSUE TITLE
Secure SDLC - Defense in Depth

### ISSUE THREAD

**Issue by houllette** [podium/elixir-secure-coding#2]
I would love to see a lesson within the Secure SDLC module surrounding Defense in Depth

Relevant Resources:
- https://csrc.nist.gov/glossary/term/defense_in_depth
- https://www.fortinet.com/resources/cyberglossary/defense-in-depth
- https://en.wikipedia.org/wiki/Defense_in_depth_(computing)

**Comment by stilwellc** [comment]
PR out I forgot to link it :)
