### ISSUE TITLE
Secure SDLC - Zero Trust Model

### ISSUE THREAD

**Issue by houllette** [podium/elixir-secure-coding#3]
I think it would be helpful to introduce the Zero Trust Model to the Secure SDLC module as a lesson and how it can be extrapolated into Elixir-land

Relevant Resources:
- https://www.cloudflare.com/learning/security/glossary/what-is-zero-trust/
- https://aws.amazon.com/blogs/publicsector/how-to-think-about-zero-trust-architectures-on-aws/
- https://blog.axway.com/learning-center/digital-security/microgateway/api-microgateway

**Comment by stilwellc** [comment]
PR out I forgot to link it :)
