### ISSUE TITLE
Return an :ok on the cookie security setup

### ISSUE THREAD

**Issue by michaeldbianchi** [podium/elixir-secure-coding#43]
Just a tiny usability thing. Happy to submit a PR myself.

Currently, the cookie security module's setup ends on building a plug connection. It's just a little strange that the return value from the cell is the actual `Plug.Conn` struct. Assuming the cell completes, it would probably be better to just return an `:ok` like the other modules

<img width="907" alt="Screenshot 2022-12-30 at 5 34 03 PM" src="https://user-images.githubusercontent.com/7072770/210118128-4cebdc3b-9dba-437e-8bbe-98b21b267231.png">

**Comment by houllette** [comment]
Thanks for the callout, @michaeldbianchi! We will be sure to include this in a planned upcoming release, but you're more than welcome to submit a PR yourself before that if you'd like to see it included sooner and/or are itching to add your name to the contributors list 😄
